/* This is an autogenerated file from a template. Do not edit this file as it will be overwritten.*/
/**
 *
 * startup_params.h
 * 
 * Startup parameters
 *
 * Component: state machine
 */ /*
 *
 * Motor Control Application Framework
 * branches/DB_MC-4361B (commit 122007, build on 2023 Dec 14)
 *
 * (c) 2017 - 2023 Microchip Technology Inc. and its subsidiaries. You may use
 * this software and any derivatives exclusively with Microchip products.
 *
 * This software and any accompanying information is for suggestion only.
 * It does not modify Microchip's standard warranty for its products.
 * You agree that you are solely responsible for testing the software and
 * determining its suitability.  Microchip has no obligation to modify,
 * test, certify, or support the software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
 * INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
 * AND FITNESS FOR A PARTICULAR PURPOSE, OR ITS INTERACTION WITH
 * MICROCHIP PRODUCTS, COMBINATION WITH ANY OTHER PRODUCTS, OR USE IN ANY
 * APPLICATION.
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL,
 * PUNITIVE, INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF
 * ANY KIND WHATSOEVER RELATED TO THE USE OF THIS SOFTWARE, THE
 * motorBench(R) DEVELOPMENT SUITE TOOL, PARAMETERS AND GENERATED CODE,
 * HOWEVER CAUSED, BY END USERS, WHETHER MICROCHIP'S CUSTOMERS OR
 * CUSTOMER'S CUSTOMERS, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES OR THE DAMAGES ARE FORESEEABLE. TO THE
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL
 * CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT
 * OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS
 * SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF
 * THESE TERMS.
 *
 *
 ******************************************************************************/
#ifndef __STARTUP_PARAMS_H
#define __STARTUP_PARAMS_H

#ifdef  __cplusplus
extern "C" {
#endif

//************** Start-Up Parameters **************

/*
 * Startup operating parameters:
 *
 * Istartup:                       1.650  A
 * Kspring:                      140.394 mNm/rad
 * omega_crit:                   381.447  rad/s
 *                                 3.643 kRPM
 * omega0:                        76.289  rad/s
 *                               728.510  RPM
 * omega_min:                     20.944  rad/s
 *                               200.000  RPM
 * omega1:                       114.940  rad/s
 *                                 1.098 kRPM
 * accel_limit_0:                491.069  rad/s^2
 *                                 4.689 kRPM/s
 * accel_limit_1:                  2.455 krad/s^2
 *                                23.447 kRPM/s
 * accel0:                       491.069  rad/s^2
 *                                 4.689 kRPM/s
 * accel1:                       670.204  rad/s^2
 *                                 6.400 kRPM/s
 * t1:                           155.354 ms
 * t2:                            57.670 ms
 * B_desired:                    736.114 uNm/(rad/s)
 * B_added:                      725.019 uNm/(rad/s)
 * damping_gain_ideal:            17.042 mA/(rad/s)
 * damping_gain_max:             105.042 mA/(rad/s)
 * damping_gain:                  17.042 mA/(rad/s)
 * damping_threshold:             45.976  rad/s
 *                               439.040  RPM
 * damping_Imax:                 220.000 mA
 * t_rampup:                      17.150 ms
 * dIdt_rampup:                   96.210  A/s
 * t_align:                        0.000  s
 * t_hold:                         0.000  s
 * t_rampdown_decay:             104.864 ms
 * Irampdown_end:                 82.500 mA
 * rampup_angle:                 -523.599 mrad
 * align_angle_delta:            523.599 mrad
 * theta_error_converge_rate:     17.453  rad/s
 *                               166.667  RPM
 */

/* first startup threshold velocity */
#define STARTUP_ACCEL0_VELOCITY_THRESHOLD       22000//3979      // Q15(  0.12143) = +728.57666 RPM         = +728.51032 RPM         + 0.0091%
/* second startup threshold velocity */
#define STARTUP_ACCEL1_VELOCITY_THRESHOLD       24000//5994      // Q15(  0.18292) =   +1.09753 kRPM        =   +1.09760 kRPM        - 0.0060%
/* threshold velocity for damping */
#define STARTUP_DAMPING_THRESHOLD            20000//2398      // Q15(  0.07318) = +439.08691 RPM         = +439.04000 RPM         + 0.0107%
#define Q15_THETADELTA (Q15(THETADELTA/180.0))
    
/* open loop startup current ramp from initial startup current to startup current */
/* motor current from end of current rampup phase to end of startup */
#define MCAPP_STARTUP_CURRENT                 4000//1238      // Q15(  0.03778) =   +1.64951 A           =   +1.65000 A           - 0.0298%
/* motor current at beginning of startup */
#define MCAPP_STARTUP_CURRENT_INITIAL            0      // Q15(  0.00000) =   +0.00000 A           =   +0.00000 A           + 0.0000%
/* maximum current amplitude used for active damping */
#define STARTUP_DAMPING_IQMAX                 165      // Q15(  0.00504) = +219.84558 mA          = +220.00000 mA          - 0.0702%
/* binary point for active damping gain */
#define STARTUP_DAMPING_SHIFT                   8
/* active damping gain */
#define STARTUP_DAMPING_GAIN                   63      // Q8(  0.24609)  =  +17.10033 mA/(rad/s)  =  +17.04174 mA/(rad/s)  + 0.3438%

//value of theta_error at transition
#define THETADELTA 10           


#define STARTUP_DELTA_T_FACTOR               1638//1311
#define STARTUP_DELTA_T_FACTOR_ACCELERATION          4
/* first startup acceleration rate */
#define STARTUP_ACCELERATION0               4000//20980      // Q15(  0.64026) = +491.07234 rad/s^2     = +491.06890 rad/s^2     + 0.0007%
/* second startup acceleration rate */
#define STARTUP_ACCELERATION1               42000//28633      // Q15(  0.87381) = +670.20373 rad/s^2     = +670.20410 rad/s^2     - 0.0001%

/* increase in current per control cycle, during current rampup */
#define STARTUP_TORQUE_RAMPUP_RATE              40      // Q15(  0.00012) =   +5.32959 mA          =   +4.81048 mA          +10.7913%

/* Current rampdown time constant = 0.104864 s */
/* current rampdown decay rate (=1/time constant) */
#define MCAPP_RAMPDOWN_DECAY_RATE             8000      // Q24(  0.00048) =   +9.53674 1/s         =   +9.53618 1/s         + 0.0059%
#define MCAPP_RAMPDOWN_DECAY_RATE_Q             24
#define MCAPP_RAMPDOWN_DECAY_SHIFT (MCAPP_RAMPDOWN_DECAY_RATE_Q - 16)

/* current rampdown end threshold */
#define MCAPP_RAMPDOWN_END_CURRENT              62      // Q15(  0.00189) =  +82.60864 mA          =  +82.50000 mA          + 0.1317%

/* align angle shift after current rampup */
#define STARTUP_RAMPUP_ANGLE                -5461      // Q15( -0.16666) = -523.56682 mrad        = -523.59878 mrad        - 0.0061%
/* align angle shift after current rampup */
#define STARTUP_ALIGN_ANGLE_DELTA            5461      // Q15(  0.16666) = +523.56682 mrad        = +523.59878 mrad        - 0.0061%
/* hold time between current rampup and acceleration */
#define STARTUP_ALIGN_TIME                      0      // Q0(  0.00000)  =   +0.00000 s           =   +0.00000 s           + 0.0000%
/* hold time between velocity rampup and current rampdown */
#define STARTUP_HOLD_TIME                       0      // Q0(  0.00000)  =   +0.00000 s           =   +0.00000 s           + 0.0000%
// PWM loops necessary for transitioning from open loop to closed loop
#define TRANSITION_STEPS   IRP_PERCALC/4

/* convergence rate (electrical frequency) for forcing angle error towards zero, during transition to closed-loop */
#define STARTUP_THETA_ERROR_CONVERGE_RATE       2330      // Q24(  0.00014) =  +17.45203 rad/s       =  +17.45329 rad/s       - 0.0072%
#define STARTUP_THETA_ERROR_CONVERGE_RATE_Q         24


#ifdef  __cplusplus
}
#endif

#endif // __STARTUP_PARAMS_H
